load("@rules_cc//cc:defs.bzl", "cc_library")

# This is the singular header file for kissfftpp.
cc_library(
  name = "kissfftpp",
  hdrs = [
    "kissfftpp.h",
  ],
  visibility = ["//visibility:public"],
)